### ISSUE TITLE
Prevent news scraping fails from breaking website

### ISSUE THREAD

**Issue by djsegal** [djsegal/julia_observer#80]
```
3071 DiscourseApi::TooManyRequests: {"errors"=>["We have a daily limit on how many times that action can be taken. Please wait 25 seconds before trying again."], "error_type"=>"rate_limit"}
3072 /usr/local/rvm/gems/ruby-2.3.3/gems/discourse_api-0.14.1/lib/discourse_api/client.rb:137:in `handle_error'
3073 /usr/local/rvm/gems/ruby-2.3.3/gems/discourse_api-0.14.1/lib/discourse_api/client.rb:122:in `request'
3074 /usr/local/rvm/gems/ruby-2.3.3/gems/discourse_api-0.14.1/lib/discourse_api/client.rb:72:in `get'
3075 /usr/local/rvm/gems/ruby-2.3.3/gems/discourse_api-0.14.1/lib/discourse_api/api/topics.rb:52:in `topic'
3076 /home/rails/julia_observer/lib/tasks/news.rake:184:in `block (3 levels) in <top (required)>'
3077 /home/rails/julia_observer/lib/tasks/news.rake:180:in `each'
3078 /home/rails/julia_observer/lib/tasks/news.rake:180:in `block (2 levels) in <top (required)>'
3079 /home/rails/julia_observer/lib/tasks/news.rake:27:in `block (3 levels) in <top (required)>'
3080 /home/rails/julia_observer/lib/tasks/news.rake:26:in `each'
3081 /home/rails/julia_observer/lib/tasks/news.rake:26:in `block (2 levels) in <top (required)>'
3082 /usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
3083 /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
3084 /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
3085 Tasks: TOP => news:discourse
3086 (See full trace by running task with --trace)
3087 update job done.
```

-------

and

-------

```
3268 rake aborted!
3269 Errno::ENOENT: No such file or directory @ rb_sysopen - tmp/news/discourse.yml
3270 /home/rails/julia_observer/lib/tasks/news.rake:13:in `block (3 levels) in <top (required)>'
3271 /home/rails/julia_observer/lib/tasks/news.rake:9:in `each'
3272 /home/rails/julia_observer/lib/tasks/news.rake:9:in `block (2 levels) in <top (required)>'
3273 /usr/local/rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
3274 /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
3275 /usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
3276 Tasks: TOP => news:make
3277 (See full trace by running task with --trace)
```

**Comment by djsegal** [comment]
resolved by: https://github.com/djsegal/julia_observer/commit/823472c713e6bb4117d6ccba0b1ce4079629b3cb
